### ISSUE TITLE
Cutoff option not working

### ISSUE THREAD

**Issue by kcamnairb** [greatfireball/ime_big_scape#1]
Hi, I can't get the cutoff option to work. When I try "--cutoffs 0.1, 0.25, 0.5, 1.0" as given in the help example, it returns "error: argument --cutoffs: invalid float value: '0.1,'". I've tried removing the commas and also just supplying a single value and that doesn't work either. What format is expected for this option?

**Comment by greatfireball** [comment]
I had the same issue... Finally I am running a job with

`--cutoffs 0.3 0.6 0.65 0.7 0.75 0.8 0.85` 

and it seems to work. I had no time to look into the code, but maybe `--cutoffs` requires two or more cutoffs to work correctly. Will let you know, if the setting above finishes without errors.

**Comment by greatfireball** [comment]
by the way, this repository is just a fork of the official repository at https://git.wageningenur.nl/medema-group/BiG-SCAPE

**Comment by greatfireball** [comment]
I recognized, that there were some commits inside the official repository. One addressing a [fix for the cutoffs option (commit 97bfde2dee)](https://git.wageningenur.nl/medema-group/BiG-SCAPE/commit/97bfde2deece7d02a24c907b99d722a379c2b487). I updated my repository to to include those commits and released a new [docker image with the tag release2018-10-18](https://hub.docker.com/r/greatfireball/ime_big_scape/).

Hope that helps @kcamnairb

**Comment by kcamnairb** [comment]
Thanks, the cutoffs option is working now.
